import React from 'react';
import { Box, Badge, Group, Text, Anchor, Tooltip } from '@mantine/core';
import { IconBrandGithub, IconExternalLink, IconStar, IconGitFork } from '@tabler/icons-react';
import styles from './ProjectCard.module.css';
// Regenerated by scripts/fetch-github-stats.mjs before each deploy, so these
// are real counts rather than hand-maintained numbers that go stale.
import githubStats from '../data/githubStats.json';

/** github.com/owner/name -> "owner/name" */
function repoSlug(url) {
  const m = /github\.com\/([^/]+)\/([^/#?]+)/.exec(url ?? '');
  return m ? `${m[1]}/${m[2].replace(/\.git$/, '')}` : null;
}

const STATUS_COLORS = {
  active: 'blue',
  completed: 'gray',
  archived: 'gray',
};

const STATUS_LABELS = {
  active: 'Active',
  completed: 'Completed',
  archived: 'Archived',
};

export function ProjectCard({ project }) {
  // A repo that is private, renamed, or not yet public simply has no entry.
  const stats = githubStats[repoSlug(project.repo)];
  const showStars = stats?.stars > 0;
  const showForks = stats?.forks > 0;

  return (
    <Box
      className={`glassCard glassCardInteractive ${styles.cardContainer}`}
      style={{ '--card-glow-rgb': 'var(--accent-code-rgb)' }}
    >
      {/* Header: Status Badge and Year */}
      <Group justify="space-between" mb="12px">
        <Badge size="sm" color={STATUS_COLORS[project.status]}>
          {STATUS_LABELS[project.status]}
        </Badge>
        <Text size="xs" c="dimmed" fw={500}>{project.year}</Text>
      </Group>

      <Text component="h3" size="lg" fw={700} mb="8px" className={styles.title}>
        {project.title}
      </Text>

      {/* Collapsed to ~2 lines until hover reveals the rest */}
      <Box className={styles.descriptionContainer}>
        <Text size="sm" c="dimmed" mb="16px" className={styles.description}>
          {project.description}
        </Text>
      </Box>

      <Group gap="6px" mb="16px" wrap="wrap">
        {project.technologies.slice(0, 3).map((tech) => (
          <Badge
            key={tech}
            size="xs"
            variant="light"
            color="var(--accent-code)"
            className={styles.techBadge}
          >
            {tech}
          </Badge>
        ))}
        {project.technologies.length > 3 && (
          <Text size="xs" c="dimmed">+{project.technologies.length - 3}</Text>
        )}
      </Group>

      {/* Zero counts are omitted rather than rendered as "0" */}
      {(showStars || showForks) && (
        <Group gap="12px" mb="16px" className={styles.statsGroup}>
          {showStars && (
            <Tooltip label={`${stats.stars} stars on GitHub`} position="top">
              <Group gap="4px">
                <IconStar size={14} style={{ opacity: 0.7 }} />
                <Text size="xs" c="dimmed">{stats.stars}</Text>
              </Group>
            </Tooltip>
          )}
          {showForks && (
            <Tooltip label={`${stats.forks} forks on GitHub`} position="top">
              <Group gap="4px">
                <IconGitFork size={14} style={{ opacity: 0.7 }} />
                <Text size="xs" c="dimmed">{stats.forks}</Text>
              </Group>
            </Tooltip>
          )}
        </Group>
      )}

      <Group gap="12px" mt="auto">
        {project.repo && (
          <Anchor
            href={project.repo}
            target="_blank"
            rel="noopener noreferrer"
            size="xs"
            className={styles.link}
          >
            <IconBrandGithub size={14} />
            GitHub
          </Anchor>
        )}
        {project.demo && (
          <Anchor
            href={project.demo}
            target="_blank"
            rel="noopener noreferrer"
            size="xs"
            className={styles.link}
          >
            <IconExternalLink size={14} />
            Demo
          </Anchor>
        )}
      </Group>

      {project.image && (
        <Box className={styles.projectImage}>
          <img src={project.image} alt="" />
        </Box>
      )}
    </Box>
  );
}
